### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by TimothyMischief** [Aaronius/hyper-cat#2]
I've tried installing with hpm and manually configuring the config file but get the following erros in the console:

```
bundle.js:1 Error: Cannot find module '/Users/timhope/.hyper_plugins/node_modules/hyper-cat'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at de.plugins.concat.map.ge (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:8503)
    at Array.map (native)
    at ie (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:8457)
    at Object.A.reload (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:6014)
    at EventEmitter.U.a.on (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:45:377742)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)de.plugins.concat.map.ge @ bundle.js:1
bundle.js:1 [Notification] Plugin load error: "hyper-cat" failed to load in the renderer process. Check Developer Tools for details.
```

I'm new to Hyper so I'm not sure if there's something I missed or if it might be a Hyper issue. I wound up getting it working by using npm to install it in the plugin directory though.

**Comment by TimothyMischief** [comment]
Actually the install is incomplete, I just get the rainbow trail, nothing else. (I don't mind it's quite a nice effect on its own.)

**Comment by Aaronius** [comment]
Thanks for reporting this @SnappyCroissant. I had a co-worker that ran into something similar to this but it wasn't apparent what was happening.  He ran `npm install` directly from the `.hyper_plugins` directory (which sounds like what you did) and everything worked fine for him afterward. It looks like others are receiving a similar message with other plugins as well: https://github.com/zeit/hyper/issues/191

Could you try the suggestion in https://github.com/zeit/hyper/issues/191#issuecomment-282262481

**Comment by TimothyMischief** [comment]
That's fixed it! Thanks :)

**Comment by Aaronius** [comment]
Good to hear!
